---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lil-eks-cli
  region: us-east-2
  tags:
    project: linkedin-learning

nodeGroups:
  - name: worker-node
    instanceType: m5.large # use General Purpose if you don't know https://aws.amazon.com/ec2/instance-types/
    desiredCapacity: 3
